# workflow name
name: Generate release-artifacts

# on events
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
            platforms: 'linux/amd64, linux/arm64, darwin/amd64, windows/amd64'
            package: 'main'
            name: 'contactmanager'
            compress: 'false'
            dest: 'build/'
